-- =============================================================================
-- V1__Initial_Schema.sql
-- -----------------------------------------------------------------------------
-- Flyway BASELINE migration for the Secure File Management System.
--
-- Provenance: generated from the LIVE MySQL 8.0 schema of `file_management_db`
-- via `mysqldump --no-data` (DDL only, no rows). It is an exact structural
-- snapshot of the running database: every table, primary key, foreign key,
-- index, unique constraint, default value and AUTO_INCREMENT column attribute
-- present at baseline time is reproduced here.
--
-- What is intentionally NOT here:
--   * No INSERT / seed / user data (schema only).
--   * No table-level `AUTO_INCREMENT=<n>` next-counter values. Those reflect how
--     many rows currently exist (data state), not structure. Stripping them lets
--     a fresh install start its counters at 1 while remaining schema-identical.
--
-- Foreign-key note: tables are emitted in alphabetical order, so some children
-- (e.g. file_permissions) reference parents (files) declared further down. We
-- disable FK checks for the duration of this script so creation order does not
-- matter, then re-enable them at the end.
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- audit_logs
-- -----------------------------------------------------------------------------
CREATE TABLE `audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action` varchar(255) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `details` varchar(1000) DEFAULT NULL,
  `performed_by` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- file_permissions
-- NOTE: the live schema carries TWO unique keys over the same column pair
-- (`unique_file_user_permission` was created by an explicit migration, while
-- `UK30c76mi2832my6tux258yjbqn` was auto-generated by Hibernate). Both are
-- reproduced here to remain an exact mirror of production.
-- -----------------------------------------------------------------------------
CREATE TABLE `file_permissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `file_id` bigint NOT NULL,
  `shared_with_user_id` bigint NOT NULL,
  `permission_type` varchar(50) DEFAULT 'VIEW_DOWNLOAD',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_file_user_permission` (`file_id`,`shared_with_user_id`),
  UNIQUE KEY `UK30c76mi2832my6tux258yjbqn` (`file_id`,`shared_with_user_id`),
  KEY `fk_permission_user` (`shared_with_user_id`),
  KEY `FKfo7bno9d0r0ieb90jxpm4pde6` (`permission_type`),
  CONSTRAINT `fk_permission_file` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_permission_user` FOREIGN KEY (`shared_with_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FKfo7bno9d0r0ieb90jxpm4pde6` FOREIGN KEY (`permission_type`) REFERENCES `permission_types` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- files
-- -----------------------------------------------------------------------------
CREATE TABLE `files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_type` varchar(20) NOT NULL,
  `file_size` bigint NOT NULL,
  `visibility` varchar(20) DEFAULT 'PRIVATE',
  `file_data` longblob,
  `uploaded_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `file_hash` varchar(64) DEFAULT NULL,
  `is_compressed` bit(1) DEFAULT NULL,
  `compressed_file_size` bigint DEFAULT NULL,
  `original_file_size` bigint DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `is_deleted` bit(1) DEFAULT NULL,
  `content_type` varchar(255) DEFAULT NULL,
  `compression_algorithm` varchar(50) DEFAULT NULL,
  `requires_decompression` bit(1) DEFAULT NULL,
  `hls_folder` varchar(255) DEFAULT NULL,
  `hls_playlist` varchar(255) DEFAULT NULL,
  `hls_generated` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_file_owner` (`owner_id`),
  CONSTRAINT `fk_file_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- folders
-- -----------------------------------------------------------------------------
CREATE TABLE `folders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `owner_id` bigint NOT NULL,
  `parent_folder_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5b5p96ewk9msg1omqhl0vttop` (`owner_id`),
  KEY `FKiohfylsa0e068vfrh56nwqv5w` (`parent_folder_id`),
  CONSTRAINT `FK5b5p96ewk9msg1omqhl0vttop` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKiohfylsa0e068vfrh56nwqv5w` FOREIGN KEY (`parent_folder_id`) REFERENCES `folders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- password_reset_otp
-- -----------------------------------------------------------------------------
CREATE TABLE `password_reset_otp` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `expiry_time` datetime(6) DEFAULT NULL,
  `otp` varchar(255) DEFAULT NULL,
  `verified` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- permission_types
-- -----------------------------------------------------------------------------
CREATE TABLE `permission_types` (
  `code` varchar(50) NOT NULL,
  `description` varchar(255) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- permissions
-- -----------------------------------------------------------------------------
CREATE TABLE `permissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- role_permissions  (join table: roles <-> permissions)
-- -----------------------------------------------------------------------------
CREATE TABLE `role_permissions` (
  `role_id` bigint NOT NULL,
  `permission_id` bigint NOT NULL,
  `id` bigint NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `fk_role_permissions_permission` (`permission_id`),
  CONSTRAINT `fk_role_permissions_permission` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_role_permissions_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- roles
-- -----------------------------------------------------------------------------
CREATE TABLE `roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- user_permissions  (join table: users <-> permissions)
-- -----------------------------------------------------------------------------
CREATE TABLE `user_permissions` (
  `permission_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`permission_id`,`user_id`),
  KEY `FKkowxl8b2bngrxd1gafh13005u` (`user_id`),
  CONSTRAINT `FKkowxl8b2bngrxd1gafh13005u` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKq4qlrabt4s0etm9tfkoqfuib1` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- user_roles  (join table: users <-> roles)
-- -----------------------------------------------------------------------------
CREATE TABLE `user_roles` (
  `user_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `fk_user_roles_role` (`role_id`),
  CONSTRAINT `fk_user_roles_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_roles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('ACTIVE','BLOCKED') NOT NULL,
  `otp` varchar(6) DEFAULT NULL,
  `otp_expiry` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
